### ISSUE TITLE
CSS 部分第15题好像也不对吧 ～=￣ω￣=～？

### ISSUE THREAD

**Issue by BuptStEve** [paddingme/Front-end-Web-Development-Interview-Question#7]
15. Q:#example位置如何变化：

```html
<p id="example">Hello</p>
```

```css
#example {margin-bottom: -5px;}
```

~~A: 向上移动5px。~~

A: 我测试为啥位置不变，不过设置 margin-top 倒是都会变╮(╯_╰)╭
